name: Pac-Man Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pac-Man contribution animation
        uses: Platane/snk@v3
        with:
          github_user_name: Basyokoo
          outputs: |
            dist/pacman-contribution-graph.svg?type=pacman
            dist/pacman-contribution-graph-dark.svg?type=pacman&palette=github-dark

      - name: Push to output-en branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output-en
          publish_dir: ./dist
          force_orphan: true
