name: Pac-Man Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Basyokoo
          games: 'pacman'

      - name: Push SVGs to output-en branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-en
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
